### ISSUE TITLE
[Docs]: Working on mlp customization

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/mlp#82]
### Documentation Revision

Hi guys,
we are working on a `mlp` customization for a client.

Is there a way to locally test/debug/troubleshoot mlp or we need to test it in a real environment?

I didn't find help on the "local development" of the tool inside the [_Contributing_ guidelines](https://github.com/mia-platform/mlp/blob/main/CONTRIBUTING.md).

Thanks.

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by davidebianchi** [comment]
Hi!
You could run tests in this way: [mia-platform/mlp@main/README.md#testing](https://github.com/mia-platform/mlp/blob/main/README.md#testing) (tests are running with envtest, so with the real kubernetes services)

If you want a real life manual test, you need to use a real environment (e.g. KinD).
